### ISSUE TITLE
Validation error: Trying to access parent frame stack values

### ISSUE THREAD

**Issue by pepyakin** [paritytech/parity-wasm#121]
The following wasm module doesn't pass validation

(in base64)
```
AGFzbQEAAAABFgVgAAF/YAABfmAAAGABfQF9YAF8AXwDBwYAAQACAwQFBAEBAQEGBwF/AUHkAAsHMwQGZnVuY18wAAAGZnVuY18xAAEGZnVuY18yAAIUaGFuZ0xpbWl0SW5pdGlhbGl6ZXIAAwr9AQYiAQF+AkACQCMARQRAQQsPCyMAQQFrJAALQYKEiBAPAAsACycCAX8BfQJ+AkAjAEUEQELIkKHChImSpMgADwsjAEEBayQAC0IACwt+AQF+AkACQCMARQRAQdYADwsjAEEBayQACwJAA0ACQCMARQRAQZOmzJgBDwsjAEEBayQACwJAAkADfwJAIwBFBEBBgoSIEA8LIwBBAWskAAsCf0H//wFFDQFB//8BCwtFBEBBiv8DDwVB//8BDwsAAAsAAAsACwAACwAACwALBwBB5AAkAAsSACAAIABbBH0gAAVDAAAAAAsLFgAgACAAYQR8IAAFRAAAAAAAAAAACws=
```

with the following output:

<details>

```
thread 'main' panicked at 'Failed to initialize module: Validation("Function #2 validation error: Trying to access parent frame stack values.")', src/libcore/result.rs:906:4
stack backtrace:
   0:        0x10cef07e3 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::h8aecd929304c9479
                               at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:        0x10ceed2cc - std::sys_common::backtrace::_print::h2713bf0620e35db5
                               at src/libstd/sys_common/backtrace.rs:68
   2:        0x10cef1ee1 - std::panicking::default_hook::{{closure}}::h11a5a11b67d49ee9
                               at src/libstd/sys_common/backtrace.rs:57
                               at src/libstd/panicking.rs:381
   3:        0x10cef1be6 - std::panicking::default_hook::h7b0af320addd8626
                               at src/libstd/panicking.rs:397
   4:        0x10cef23c5 - std::panicking::begin_panic::hf394ece603bb87f5
                               at src/libstd/panicking.rs:577
   5:        0x10cef225e - std::panicking::begin_panic::hf394ece603bb87f5
                               at src/libstd/panicking.rs:538
   6:        0x10cef2132 - std::panicking::try::do_call::h2275ef654078256f
                               at src/libstd/panicking.rs:522
   7:        0x10cef2092 - std::panicking::try::do_call::h2275ef654078256f
                               at src/libstd/panicking.rs:498
   8:        0x10cf25323 - <core::ops::range::Range<Idx> as core::fmt::Debug>::fmt::hbfacf08ac38f19d1
                               at src/libcore/panicking.rs:71
   9:        0x10cda354d - core::result::unwrap_failed::h450ee8d351a10480
                               at /Users/travis/build/rust-lang/rust/src/libcore/macros.rs:23
  10:        0x10cda2f61 - <core::result::Result<T, E>>::expect::h14f148c8875b2276
                               at /Users/travis/build/rust-lang/rust/src/libcore/result.rs:799
  11:        0x10cdabaa2 - validate::main::h48b830043e2dac38
                               at examples/validate.rs:29
  12:        0x10cefd1ae - panic_unwind::dwarf::eh::read_encoded_pointer::h2701a9f9f2c1e569
                               at src/libpanic_unwind/lib.rs:99
  13:        0x10cef2688 - rust_panic
                               at src/libstd/panicking.rs:459
                               at src/libstd/panic.rs:365
                               at src/libstd/rt.rs:58
  14:        0x10cdabb34 - validate::main::h48b830043e2dac38
```

</details>

**Comment by pepyakin** [comment]
Reduced example:

wasm (in base64)
```
AGFzbQEAAAABEgRgAAF/YAAAYAF9AX1gAXwBfAMCAQAFBAEBAQEGBwF/AUHkAAsKJwElAgF/AX0C
fwJ/An8CfwJ/AQN/AQJ/QQENAUH//wELCwsLCwsLCw==
```

wabt wasm2wast
```
(module
  (type (;0;) (func (result i32)))
  (type (;1;) (func))
  (type (;2;) (func (param f32) (result f32)))
  (type (;3;) (func (param f64) (result f64)))
  (func (;0;) (type 0) (result i32)
    (local i32 f32)
    block i32  ;; label = @1
      block i32  ;; label = @2
        block i32  ;; label = @3
          block i32  ;; label = @4
            block i32  ;; label = @5
              nop
              loop i32  ;; label = @6
                nop
                block i32  ;; label = @7
                  i32.const 1
                  br_if 1 (;@6;)
                  i32.const 32767
                end
              end
            end
          end
        end
      end
    end)
  (memory (;0;) 1 1)
  (global (;0;) (mut i32) (i32.const 100)))
```

**Comment by pepyakin** [comment]
Ah, I see what is going on:

https://github.com/paritytech/parity-wasm/blob/e85a8dec4207cb4c84d90da2bd65d1aa65f486f0/src/interpreter/validator.rs#L486-L492

`br_if L` (where L is a loop label) trying to pop value as result of a block. However, loop blocks are always have arity of 0, i.e. can't return results. Thus when branching to the loop header we shouldn't pop any operands from the stack.
